### ISSUE TITLE
MCA: "ValueError: All values in X should be positive"

### ISSUE THREAD

**Issue by selib** [MaxHalford/prince#19]
I have a dataframe like this:
restDf.head()
```
  | a | b | c | d
-- | -- | -- | -- | --
109 | 4 | 4 | 0
2 | 4 | 4 | 0
243 | 4 | 6 | 1
130 | 3 | 4 | 0
181 | 4 | 6 | 1
```

trying to run:

```
import prince
mca = prince.MCA()
test = mca.fit(restDf)
```

gives me:
```

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-75-d72ed9bacef2> in <module>()
      2 
      3 mca = prince.MCA(n_components=2)
----> 4 test = mca.fit(restDf)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\prince\mca.py in fit(self, X, y)
     26 
     27         # Apply correspondence analysis to the indicator matrix
---> 28         super().fit(X)
     29 
     30         # Compute the total inertia

~\AppData\Local\Continuum\anaconda3\lib\site-packages\prince\ca.py in fit(self, X, y)
     24         # Check all values are positive
     25         if np.any(X < 0):
---> 26             raise ValueError("All values in X should be positive")
     27 
     28         if isinstance(X, pd.DataFrame):

ValueError: All values in X should be positive

```

This also happens when I run the program with the same dataframe where everything <=0 is replaced with a positive number:
restDf2.head()
```
  | a | b | c | d
-- | -- | -- | -- | --
109 | 4 | 4 | 42069
2 | 4 | 4 | 42069
243 | 4 | 6 | 1
130 | 3 | 4 | 42069
181 | 4 | 6 | 1
```

Any help?

**Comment by MaxHalford** [comment]
Hey,

Can you send me the CSV file you're using? My email address is maxhalford25@gmail.com.

Regards.

**Comment by selib** [comment]
sent.

**Comment by MaxHalford** [comment]
I can't reproduce your error. I just ran the following piece of code and it worked fine.

```python
import pandas as pd
import prince

df = pd.read_csv('output_s5.csv', sep=';', index_col=0)
mca = prince.MCA().fit(df)
```

**Comment by selib** [comment]
If I run that code snippet, I still get the same error. Could the error be related to pandas or scikit or something?

I'm using everything that came with Anaconda 1.7.0.

**Comment by MaxHalford** [comment]
This is a weird one for sure. Have you done `pip install prince --upgrade`?

**Comment by selib** [comment]
Woops, I'm actually on 5.1.0 as well. 1.7.0 is the version of my Anaconda Navigator.

Upgrading prince didn't change anything for me either. (wouldve surprised me if it did, I just installed it a few hours ago)

**Comment by selib** [comment]
I added a print(X.head()) in ca.py

before the 
`            raise ValueError("All values in X should be positive")`
apparently 
the original dataframe
```
     a  b  c      d
0  109  4  4  42069
1    2  4  4  42069
2  243  4  6      1
3  130  3  4  42069
4  181  4  6      1
```

gets converted to

```
     a  b  c   d
0  109  4  4  85
1    2  4  4  85
2  -13  4  6   1
3 -126  3  4  85
4  -75  4  6   1
```

somewhere

**Comment by selib** [comment]
Ok I just identified where the values are converted into negative values,

It happens in mca.py here:

```
        # One-hot encode the dataset to retrieve an indicator matrix
        if isinstance(X, pd.DataFrame):
            X = pd.get_dummies(X).astype(np.int8)
        else:
            X = pd.get_dummies(pd.DataFrame(X)).astype(np.int8)

```

**Comment by MaxHalford** [comment]
Okay I think I've found the error. Give me a minute and I'll push a fix.

**Comment by MaxHalford** [comment]
You can upgrade to version 0.3.3, the bug shouldn't occur anymore. Thanks a lot for bringing it here! It seems like I have to write some more unit tests.

**Comment by selib** [comment]
Thanks for the fix, man.

But now I have the following error:


```
  File "<ipython-input-1-dffe8bc1f7e1>", line 1, in <module>
    runfile('D:/repos/service-recommender-system/src/filterBEZ.py', wdir='D:/repos/service-recommender-system/src')

  File "C:\Users\YEDS\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\YEDS\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/repos/service-recommender-system/src/filterBEZ.py", line 36, in <module>
    mca = prince.MCA().fit(df)

  File "C:\Users\YEDS\AppData\Local\Continuum\anaconda3\lib\site-packages\prince\mca.py", line 29, in fit
    super().fit(X)

  File "C:\Users\YEDS\AppData\Local\Continuum\anaconda3\lib\site-packages\prince\ca.py", line 56, in fit
    self.U_, self.s_, self.V_ = svd.compute_svd(S, self.n_components, self.n_iter, self.engine)

  File "C:\Users\YEDS\AppData\Local\Continuum\anaconda3\lib\site-packages\prince\svd.py", line 32, in compute_svd
    U, V = extmath.svd_flip(U, V)

  File "C:\Users\YEDS\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\extmath.py", line 529, in svd_flip
    v *= signs[:, np.newaxis]

ValueError: operands could not be broadcast together with shapes (306,2) (2,1) (306,2) 
```

**Comment by selib** [comment]
The same error appears if I use prince.PCA() but the lsat error line change to: 
`ValueError: operands could not be broadcast together with shapes (4,2) (2,1) (4,2) `

Using PCA() from `from sklearn.decomposition import PCA` runs without issues

**Comment by MaxHalford** [comment]
Just fixed it! Upgrade again :). I should have spotted this mistake earlier. It's due to the fact that I was using a different SVD engine for testing. Should be all good now.

**Comment by selib** [comment]
Perfect! thank you!
