### ISSUE TITLE
FAMD.column_correlation throws AttributeError

### ISSUE THREAD

**Issue by jhaugheyalt** [MaxHalford/prince#65]
Looks like this might be something similar to #41 but slightly different, so maybe not.

When calling FAMD.column_correlation() on a DataFrame with a mix of continuous and categorical data, an error is thrown. The example below is a slightly modified version of the wine data, with Oak type included as a categorical:
```python
# set up data
X = pd.DataFrame(
    data=[
        [1, 6, 7, 2, 5, 7, 6, 3, 6, 7],
        [5, 3, 2, 4, 4, 4, 2, 4, 4, 3],
        [6, 1, 1, 5, 2, 1, 1, 7, 1, 1],
        [7, 1, 2, 7, 2, 1, 2, 2, 2, 2],
        [2, 5, 4, 3, 5, 6, 5, 2, 6, 6],
        [3, 4, 4, 3, 5, 4, 5, 1, 7, 5]
    ],
    columns=['E1 fruity', 'E1 woody', 'E1 coffee',
             'E2 red fruit', 'E2 roasted', 'E2 vanillin', 'E2 woody',
             'E3 fruity', 'E3 butter', 'E3 woody'],
    index=['Wine {}'.format(i+1) for i in range(6)]
)
X['Oak type'] = ['a', 'b', 'b', 'b', 'a', 'a']

# instantiate and fit
famd = prince.FAMD(
    n_components=2,
    n_iter=3,
    copy=True,
    check_input=True,
    engine='auto',
    random_state=42
)
famd = famd.fit(X)

# errors here
famd.column_correlations(X)
```
With the following traceback:
```python
Traceback (most recent call last):
  File "<ipython-input-262-22af72d49038>", line 1, in <module>
    famd.column_correlations(X)
  File "C:\Users\test\AppData\Roaming\Python\Python35\site-packages\prince\mfa.py", line 193, in column_correlations
    for component in row_pc.columns
  File "C:\Users\test\AppData\Roaming\Python\Python35\site-packages\prince\mfa.py", line 193, in <dictcomp>
    for component in row_pc.columns
  File "C:\Users\test\AppData\Roaming\Python\Python35\site-packages\prince\mfa.py", line 191, in <dictcomp>
    for feature in X_global.columns
  File "C:\Users\test\Anaconda3\envs\test\lib\site-packages\pandas\core\series.py", line 2105, in corr
    min_periods=min_periods)
  File "C:\Users\test\Anaconda3\envs\test\lib\site-packages\pandas\core\nanops.py", line 76, in _f
    return f(*args, **kwargs)
  File "C:\Users\test\Anaconda3\envs\test\lib\site-packages\pandas\core\nanops.py", line 1102, in nancorr
    return f(a, b)
  File "C:\Users\test\Anaconda3\envs\test\lib\site-packages\pandas\core\nanops.py", line 1112, in _pearson
    return np.corrcoef(a, b)[0, 1]
  File "C:\Users\test\Anaconda3\envs\test\lib\site-packages\numpy\lib\function_base.py", line 2522, in corrcoef
    c = cov(x, y, rowvar)
  File "C:\Users\test\Anaconda3\envs\test\lib\site-packages\numpy\lib\function_base.py", line 2427, in cov
    avg, w_sum = average(X, axis=1, weights=w, returned=True)
  File "C:\Users\test\Anaconda3\envs\test\lib\site-packages\numpy\lib\function_base.py", line 427, in average
    if scl.shape != avg.shape:
AttributeError: 'float' object has no attribute 'shape'
```
Not sure how to approach, let me know if there's anything I can help with

**Comment by MaxHalford** [comment]
Hey,

Not sure what's going on, I'll take a look at this before the weekend. Thanks for the detailed issue!

**Comment by MaxHalford** [comment]
I just fixed, it will be in the next release.
